project_id = "oqizedfudvjufqchlaqy"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[studio]
enabled = true
port = 54323
api_url = "https://oqizedfudvjufqchlaqy.supabase.co"

[edge_runtime]
policy = "per_worker"
